# Generated by Django 4.2.4 on 2023-12-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostGroup', '0002_commentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgroup',
            name='total_calificaciones',
            field=models.IntegerField(default=0),
        ),
    ]
