# Generated by Django 4.2.4 on 2023-12-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_post_comentarios_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='contenido',
        ),
    ]
