# Generated by Django 4.2.4 on 2023-11-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
