# Generated by Django 4.2.4 on 2023-10-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_preferencia_remove_userprofile_preferencias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferencias',
        ),
        migrations.DeleteModel(
            name='Preferencia',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferencias',
            field=models.TextField(default='ValorPredeterminado'),
        ),
    ]
