# Generated by Django 4.2.4 on 2023-10-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_userprofile_preferencias_delete_preferencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nivel_de_dominio',
            field=models.TextField(max_length=50),
        ),
    ]
