# Generated by Django 4.2.4 on 2023-11-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_userprofile_preferencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nivel_de_dominio',
            field=models.IntegerField(max_length=50),
        ),
    ]
