# Generated by Django 4.2.4 on 2023-12-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0004_groupinvitation'),
        ('User', '0017_alter_userprofile_nivel_de_dominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='miembross', to='Group.group'),
        ),
    ]
